@GetAdults_HostAddress = http://localhost:5137
@Docker_HostAddress = http://localhost:5005

GET {{GetAdults_HostAddress}}/Adults/
Accept: application/json

###
GET {{Docker_HostAddress}}/Adults/
Accept: application/json